ORIENTATION_TESTER_BLOCK = "minecraft:furnace"
STATE_DIR = "/state"
MIN_FUEL_LEVEL = 100
WS_URL = "ws://127.0.0.1:8000"

return { WS_URL = WS_URL, STATE_DIR = STATE_DIR, TIMEZONE = TIMEZONE, ORIENTATION_TESTER_BLOCK = ORIENTATION_TESTER_BLOCK, MIN_FUEL_LEVEL = MIN_FUEL_LEVEL}