ORIENTATION_TESTER_BLOCK = "minecraft:furnace"
STATE_DIR = "/state"
MIN_FUEL_LEVEL = 100

return { STATE_DIR = STATE_DIR, TIMEZONE = TIMEZONE, ORIENTATION_TESTER_BLOCK = ORIENTATION_TESTER_BLOCK, MIN_FUEL_LEVEL = MIN_FUEL_LEVEL}